name: release

on:
  push:
    tags:
      - 'version-*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Prepare
        run: build/make_release -w ${{ github.workspace }} -t ${{ runner.temp }}/tmp -o ${{ runner.temp }}/out
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ runner.temp }}/out/release_notes.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
